### ISSUE TITLE
Strange interaction with fugitive

### ISSUE THREAD

**Issue by sarahsturgeon** [EinfachToll/DidYouMean#10]
While in a file which was opened by DidYouMean, I'm unable to use https://github.com/tpope/vim-fugitive commands. 

`:Gstatus` produces `E492: Not an editor command: Gstatus` 
`:Git status` produces `E464: Ambiguous use of user-defined command`

These commands work just fine if I open my desired file directly.

Expected behavior:
Commands from vim-fugitive should work in files opened by DidYouMean.

**Comment by EinfachToll** [comment]
I can't confirm the issue. For me, it works. Can you provide a more concrete, minimal example?

**Comment by sarahsturgeon** [comment]
### Scenario 1
```
brandon@brandon-VirtualBox:~/Code/example/foobar$ ls
foo.bar  foobar.baz
brandon@brandon-VirtualBox:~/Code/example/foobar$ git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	foo.bar
	foobar.baz

nothing added to commit but untracked files present (use "git add" to track)
brandon@brandon-VirtualBox:~/Code/example/foobar$ vim foo

---------------------------------------------------------------------------
Did you mean:
1. foo.bar
2. foobar.baz
Type number and <Enter> or click with mouse (empty cancels): 1
---------------------------------------------------------------------------
```
In this scenario, `:Gstatus` will print the error message `E492: Not an editor command: Gstatus`.


### Scenario 2
```
brandon@brandon-VirtualBox:~/Code/example/foobar$ ls
foo.bar  foobar.baz
brandon@brandon-VirtualBox:~/Code/example/foobar$ git status
On branch master

Initial commit

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	foo.bar
	foobar.baz

nothing added to commit but untracked files present (use "git add" to track)
brandon@brandon-VirtualBox:~/Code/example/foobar$ vim foo.bar
```
In this scenario, `:Gstatus` will create a horizontal split containing the output of `git status`

**Comment by EinfachToll** [comment]
Can you test the version from this branch? https://github.com/EinfachToll/DidYouMean/tree/test-autocmds

**Comment by sarahsturgeon** [comment]
That seems to work! I'm able to run `:Gstatus` and get a horizontal split with `git status`'s output!

**Comment by EinfachToll** [comment]
Ok, so I merged the branch into master.

**Comment by sarahsturgeon** [comment]
Thanks! :)
