### ISSUE TITLE
Filenames with spaces

### ISSUE THREAD

**Issue by klaernie** [EinfachToll/DidYouMean#7]
Hi there,

I just wanted to use DidYouMean on a filename with spaces, but upon selecting one of the options vim refused to open it with the error messages
```
Did you mean:
1. Bewerbung - Vorlage 2016.pdf
2. Bewerbung - Vorlage 2016.tex
3. Bewerbung - Vorlage 2016.aux
4. Bewerbung - Vorlage 2016.log
5. Bewerbung - Vorlage 2016.out
Type number and <Enter> or click with mouse (empty cancels): 2Error detected while processing function <SNR>42_didyoumean:
line   27:
E172: Only one file name allowed: :edit Bewerbung - Vorlage 2016.tex
```

It would be nice if this case would also be covered.

Thanks for your awesome plugin, I use it every day.

**Comment by EinfachToll** [comment]
Strange that nobody (including me) encountered this issue before. Anyway, that was easy to fix.

**Comment by klaernie** [comment]
Thanks!
