### ISSUE TITLE
Do not prompt for single file

### ISSUE THREAD

**Issue by jalanb** [EinfachToll/DidYouMean#8]
On my machine there exists a file at ~/jab/todo.txt. If I edit it with vim from command line, like
```shell
$ vim ~/jab/todo.txt
```
then the file is opened normally, and away I go. However, if I use single-quotes around the filename then DidYouMean catches it and offers me a menu:
```shell
$ vim '~/jab/todo.txt'
Did you mean:
1. /Users/jab/jab/todo.txt
Type number and <Enter> or click with mouse (empty cancels):
```

I think that is good in that the `~` has been caught and expanded correctly (which was suppressed at shell by use of single quotes). But it does seem superfluous to offer a menu with only one item, and I think that DidYouMean should bypass the menu in that case and go straight to allowing vim to open the file.

**Comment by EinfachToll** [comment]
Cool, I didn't know DidYouMean catches cases like this too. But I think prompting is still the right thing, so that the user can decide if they really want to open the file '~/bla' or '/home/…/bla' instead.
